baseURL = 'https://example.org/'
languageCode = 'en-uk'
title = 'DADMAC'
theme = 'simple'


[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'News'
    pageRef = '/news'
    weight = 20
[[menus.main]]
    name = 'Flying Field'
    pageRef = '/field'
    weight = 30
[[menus.main]]
    name = 'Contact'   
    pageRef = '/contact' 
    weight = 40
[[menus.main]]
    name = 'Membership'   
    pageRef = '/membership' 
    weight = 50    
